### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by sany3001** [snhobbs/ModbusSniffer#3]
I have tried a bit to make things working, but I was not fully successful. My biggest problem is to recognize request / response frames.

**Comment by Ekristoffe** [comment]
Personally I am still using it.
I found the end of frame timing is really critical.

**Comment by 3100jisa** [comment]
Are you using this as is? Or have you made some modifications you want to share?

**Comment by snhobbs** [comment]
> I have tried a bit to make things working, but I was not fully successful. My biggest problem is to recognize request / response frames.

Can you post your setup details and issue so I can look into it?

**Comment by sany3001** [comment]
> > I have tried a bit to make things working, but I was not fully successful. My biggest problem is to recognize request / response frames.
> 
> Can you post your setup details and issue so I can look into it?

Hello! Thanks for interest. However I have moved to https://github.com/Ekristoffe/ModbusSniffer which does all what I need.
